### ISSUE TITLE
enabling CSS grids in Firefox

### ISSUE THREAD

**Issue by captainbrosset** [Igalia/css-grid-layout#1]
CSS Grids is currently being implemented in Firefox.
The bug to follow is: https://bugzilla.mozilla.org/show_bug.cgi?id=616605
I don't exactly know the current state of the implementation, but a lot of work seems to be going to it these days.
It's hidden behind the flag `layout.css.grid.enabled` in `about:config`.

So, Firefox should be listed on the `enable.html` page.

**Comment by mrego** [comment]
Yes, we were aware of the work on Firefox but forgot to update the page.

It's updated now and I've also included the prefixes in IE and WebKit and a link to the polyfill.

Thanks for reporting it!
